### ISSUE TITLE
keyerror for empty sdc list in volume

### ISSUE THREAD

**Issue by wallnerryan** [swevm/scaleio-py#10]
left a comment on an addition. Seems to me no SDC's mapped to a volume is still a valid volume, instead of having to err, an empty list should be expected.

@swevm thoughts?

https://github.com/swevm/scaleio-py/commit/305285b02a02068fa33691a68e74a7e36d9915cb#diff-db2d7b7c498186daaf6fa8cac59dc832R676

**Comment by swevm** [comment]
That's true. In ScaleIO volumes and snapshots are basically the same and do not depend on a SDC. 
It make sense to return a empty list.

**Comment by wallnerryan** [comment]
@swevm OK, glad were on the same page, I can commit a fix if needed, just lmk.

**Comment by swevm** [comment]
Feel free to commit a fix. 

Btw I created a local branch on the plane back home were I added some FaultSet and protection domain functions. Need to test if the IM wrapper can handle FaultSet creation during installation before I merge with master.

**Comment by wallnerryan** [comment]
Should get a chance to test with your newest push today/tomorrow. On a long flight to cfsummit today. Like the name change for create_volume()

I'll commit a patch for fixing this to return an empty list, we may want to include a log message that it's empty, for debugging reasons, this way it's clear what's being returned.

**Comment by wallnerryan** [comment]
One way we could do this, (listed below) No need to merge yet, but my thought is we can make debug aware the list is empty, if though its valid, the person using the API may want this info, but maybe this in unnecessary 

https://github.com/wallnerryan/scaleio-py/tree/sdclist_fix_10
https://github.com/wallnerryan/scaleio-py/commit/7c24a403e5535e11d27aa13c4f561c9bce8a2223

**Comment by swevm** [comment]
Please create a PR

**Comment by wallnerryan** [comment]
https://github.com/swevm/scaleio-py/pull/15
