### ISSUE TITLE
requests 2.5.1 dependency

### ISSUE THREAD

**Issue by wallnerryan** [swevm/scaleio-py#29]
I've been testing this with requests==2.4.3 succesfully, is there a reason you specifically need 2.5.1?

If this is ok, would like to request to make the dep `requests >= 2.4.3, <=2.5.1` ?

**Comment by swevm** [comment]
No reason at all. 2.5.1 was latest at the time. Let's lower req to 2.4.3 then

**Comment by wallnerryan** [comment]
:+1: great thanks @swevm , maybe even `requests >= 2.4.3` that way 2.4.3 or 2.5.1 can be used.
