### ISSUE TITLE
Logging should be configurable

### ISSUE THREAD

**Issue by wallnerryan** [swevm/scaleio-py#3]
In line https://github.com/swevm/scaleio-py/blob/master/scaleiopy/scaleio.py#L442 the logger is initialized to DEBUG.

A suggestion would be to make this configurable during creation of the ScaleIO object, via an attribute like `debug=True` or `verbose=True`

Configuring logging consistently will help. 

Also even if we grab the the logger with getLogger and set the log level, various print statements as like `print "*** DEBUG Login() ***"` exist like on line https://github.com/wallnerryan/scaleio-py/blob/master/scaleiopy/scaleio.py#L447. These should be set to logger statements to help with consistency.

Thoughts? I can create a pull request for this if you'd like.

@swevm

**Comment by swevm** [comment]
As you point it there's still some print statements here and there. Haven't had time to add proper logging.

Feel free to add a pull request. 

Btw. You happen to be at EMC World this week?

**Comment by wallnerryan** [comment]
Thanks, will do. and no unfortunately not, will be at CF Summit next week though

**Comment by wallnerryan** [comment]
@swevm  been testing one way to do this, lmk if you'd like a PR, or want to discuss.

https://github.com/wallnerryan/scaleio-py/tree/feat_enable_configlogging
https://github.com/wallnerryan/scaleio-py/commit/8cde85dfc7747673a226c1516bb83ddb03561907

# configure logging level

```
>>> ScaleIO("http://192.168.50.12", "ScaleIO", "password", debugLevel="WARNING")
2015-05-10 21:42:47,939: DEBUG scaleio:__init__ | Logger initialized!
<ScaleIO> @ 4356920720:
                _api_url: http://192.168.50.12
              _logged_in: False
               _password: password
                _session: <requests.sessions.Session object at 0x103f98c90>
               _username: ScaleIO
             _verify_ssl: False
                  logger: <logging.Logger object at 0x103b1ad90>
>>> s = ScaleIO("http://192.168.50.12", "ScaleIO", "password", debugLevel="WARNING")
2015-05-10 21:42:55,893: DEBUG scaleio:__init__ | Logger initialized!
```

configure a log level that doesnt make sense

```
>>> ScaleIO("http://192.168.50.12", "ScaleIO", "password", debugLevel="FOO")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "scaleiopy/scaleio.py", line 468, in __init__
    level=self._get_log_level(debugLevel))
  File "scaleiopy/scaleio.py", line 496, in _get_log_level
    raise Exception("UnknownLogLevelException: enter a valid log level")
Exception: UnknownLogLevelException: enter a valid log level
```

**Comment by wallnerryan** [comment]
Here is the PR for the above - https://github.com/swevm/scaleio-py/pull/14
